site_name: Trabalho de Compiladores
site_description: Projeto desenvolvido na disciplina Compiladores 1 do curso de Engenharia de Software da UnB
repo_url: https://github.com/Akaeboshi/comp1-equipe12-Interpretador

theme:
  name: material
  language: pt
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list



nav:
  - Início: index.md
  - Escopo da Linguagem: escopo.md
  - Gramática Formal (CGF): gramatica.md
  - Documento de Referência: referencia.md
  - Referência de tradução: ir_to_js.md

